### ISSUE TITLE
Precission of math package is limited to two decimal positions

### ISSUE THREAD

**Issue by manolinux** [PresearchOfficial/presearch-packages#100]
A calculation like:

0.002 / 16

shows 0.00  in browser (due to excessive limited decimal), when with at least 8 decimals, should be:

0,000125

Problematic lines can be these:

```
   return `
    <div class="mainCol mathContain">
      <p class="firstDigts">${query}</p>
      <h1>${typeof data === "number" ? data.toFixed(2): ``}</h1>
      ${data && data.value ? `<h1>${data.value.toFixed(2)}</h1>\` : ``}
    </div>`
``` 

in math package, file index.js

Should be easy to return a better precission (at least 8 positions, with proper rounding).

**Comment by jejopl** [comment]
It's fixed already, thanks!
