### ISSUE TITLE
Change Login name

### ISSUE THREAD

**Issue by coderbm1** [PresearchOfficial/presearch-packages#104]
**Describe the bug**
At this moment, on top right is button "Register or **Login**", it should be "**Log in**".
(as an activity)

**To Reproduce**
1. Go to https://www.presearch.org/
2. See on top right

**Expected behavior**
The mentioned name is correct.

**Comment by JoshuaPaulBarnard** [comment]
Hi @coderbm1! 

This typo has been totally resolved, and it has been changed to say "Sign up to Earn".  
![image](https://github.com/PresearchOfficial/presearch-packages/assets/20632243/a03fbf5d-d2b5-4453-a8e6-cb5f6b332533)

I hope this resolves your issue!  :-D
