### ISSUE TITLE
Weird view of search results

### ISSUE THREAD

**Issue by coderbm1** [PresearchOfficial/presearch-packages#105]
**Describe the bug**
From time to time, after typing some words for search (with Presearch on search bar set as default), there are a HTML structures in results.

**To Reproduce**

    Type words for search
    See the results with 'HTML structure

Example (typed 'medytacja wiki'):

> Medytacja – Wikipedia, wolna encyklopedia
> pl.wikipedia.org/wiki/Medytacja
> <a href="#" aria-label="Opcje wyników" aria-expanded="false" aria-haspopup="true" role="button" jsaction=" (...) jsaction="keydown:Xiq7wd;mouseover:pKPowd;mouseout:O9KS" data-ved="(...) l">Kopia
> <a href="/search?q=related:https://pl.wikipedia.org/wiki/Medytacja_mindfulness+medytacja+wiki&sa=X&ved=(...) >Podobne

**Expected behavior**
The result is readable.

**Desktop (please complete the following information):**
1.32.115 Chromium 96.0
Windows 10

**Comment by treygrainger** [comment]
Thanks for the feedback. This is related to some parsing issues in the Presearch node and not to the `presearch-packages` code base. We try to address these kinds of issues quickly when we see them. 

I've added this query to our nodes backlog to look at. I'm not seeing the HTM structure for this one currently, but it seems there may be some improvements we can make still. Thanks for the report!
