### ISSUE TITLE
add % function

### ISSUE THREAD

**Issue by acrobcrypto** [PresearchOfficial/presearch-packages#113]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JoshuaPaulBarnard** [comment]
Hi @acrobcrypto,

Thank you for raising the issue. Could you please provide more details about what you mean by "add % function"? Are you referring to a modulo operation, percentage calculation, string formatting, or something else? Any additional context or examples would be very helpful.

Thanks!
