### ISSUE TITLE
Improvement for pod-header vertical-center category_name

### ISSUE THREAD

**Issue by mbiesiad** [PresearchOfficial/presearch-packages#121]
**Describe the bug**
Mentioned parts are hiding.

**To Reproduce**
1. Go to the 'presearch.org', type something for search
ie. https://presearch.org/results?q=Presearch
2. Click on 'More Options' button
3. Change browser window size to the smallest
4. See the issue

**Expected behavior**
Mentioned parts still looks fine after action described above.

**Screenshots**
Screenshot - normal view:
![image](https://user-images.githubusercontent.com/18367606/154795542-7b5ba3d0-2823-48d5-a1f0-403282614220.png)

Screenshot - smaller view (OK):
![image](https://user-images.githubusercontent.com/18367606/154795582-189dfb8b-9770-4e5c-bb44-3f8ed3de29a2.png)

Screenshot - smaller view (incorrect, overlapping):
![image](https://user-images.githubusercontent.com/18367606/154795600-fbcdff3d-53df-4bf9-9a17-a0369d2c36d8.png)

Screenshot - smallest view (incorrect):
![image](https://user-images.githubusercontent.com/18367606/154795650-e4d58aa2-c709-486b-b035-7c9a34ce5855.png)

Best wishes,
Michal

**Comment by jejopl** [comment]
Thanks @mbiesiad, it has been fixed and it should be pushed to production soon

**Comment by mbiesiad** [comment]
My pleasure! Sounds great

**Comment by jejopl** [comment]
Thanks @mbiesiad, the fix has been pushed to production 🙏

**Comment by mbiesiad** [comment]
My pleasure! Sounds great 🎉
