### ISSUE TITLE
Arithmetic operator cannot be removed

### ISSUE THREAD

**Issue by mbiesiad** [PresearchOfficial/presearch-packages#123]
**Describe the bug**
Arithmetic operator cannot be removed using DEL button. 

**To Reproduce**
1. Go to https://engine.presearch.org/search?q=calculator
2. Type 2+ or 3 *
3. Try undo last typed char (in this case: + or *)
4. See issue

**Expected behavior**
Deleting arithmetic operator (+, -. *, /) is allowed, similar like currently for typed last number.

**Additional context**
It's a little bit similar like https://github.com/PresearchOfficial/presearch-packages/issues/124 but use case is little different.
Here user wants to remove the arithmetic mark to correct the last entered number or even change the operator (there, user accidentally entered an artitmetic wrongly and wants to easily change it).

Best wishes,

**Comment by Hkataya** [comment]
Hey @mbiesiad,
I implemented a fix for this issue and raised a PR for it. This is my first contribution to the project though so not sure who should review the [PR](https://github.com/PresearchOfficial/presearch-packages/pull/134).

**Comment by mbiesiad** [comment]
Hi Hkataya, sounds great! 🎉

**Comment by jejopl** [comment]
@Hkataya pushed your PR, good job 👍
