### ISSUE TITLE
6 Vulnerabilities - 5 High and 1 Critical

### ISSUE THREAD

**Issue by rajagottumukkala** [PresearchOfficial/presearch-packages#138]
There are multiple vulnerabilities upon doing `npm install`. 1 is Critical. Most are easier to fix. May be its better to fix before we add more dependencies with all upcoming packages. @jejopl @treygrainger 

As per changelog, seems like `mathsteps` package is no longer used. But this is still appears as a dependency. This is triggering the `critical` vulnerability as it depends on older version of `mathjs` package. 
![image](https://user-images.githubusercontent.com/7087542/159537059-22699c97-e88b-4bc3-b57c-d90b8b0355d5.png)

Couple of other high vulnerabilities are also because of the same package.

All others can be fixed with `npm audit fix'

 I can submit a pull request if you are okay for me to modify outside a package

**Comment by jejopl** [comment]
Hey @rajagottumukkala, it's a leftover from `mathsteps` package, which is no longer available. I'm removing mathsteps dependency from package.json - this will fix this warning
