### ISSUE TITLE
Add image source

### ISSUE THREAD

**Issue by mbiesiad** [PresearchOfficial/presearch-packages#151]
**Is your feature request related to a problem? Please describe.**
It would be really nice to see a source of the displayed images (images tab).
It would also improve end-user security.

Repro steps:
1. Go to: https://presearch.com/ and type searching phrase/word 
2. Click 'Images' tab
3. See the issue - displayed photos without info about the source
Example: https://presearch.com/search?q=eagle -> https://presearch.com/images?q=eagle

**Describe the solution you'd like**
Display short info about images sources, ie.: below the image.

**Describe alternatives you've considered**
Other way, after hover the image - display the link source of image.

**Additional context**
See how it looks like with Google or DuckDuckGo for instance.

Best wishes,

**Comment by jejopl** [comment]
Good call @mbiesiad. This has been pushed to production as well

**Comment by mbiesiad** [comment]
Awesome! ✨ Great work 🚀
