### ISSUE TITLE
Weather package is too eager

### ISSUE THREAD

**Issue by theLeftTenant** [PresearchOfficial/presearch-packages#157]
**Describe the bug**
The weather package appears when it isn't relevant

**To Reproduce**
1. Search "windows server 2022
2. Observe weather results for "Zorkot-**Server**, Khowst, Afghanistan" at top of page

**Expected behavior**
Search results don't include weather package

**Desktop**
 - OS: Windows 10
 - Browser: Firefox w/ Presearch plugin
 - Version: 104.0b10 (64-bit)

**Comment by jejopl** [comment]
@theLeftTenant nice catch! This has been fixed, thanks!
