### ISSUE TITLE
create-package.sh script is not working on windows

### ISSUE THREAD

**Issue by jejopl** [PresearchOfficial/presearch-packages#16]
`bin/create-package.sh` script is not working on Windows. So, `npm run create-package <packageName>` will not work either

**Comment by BDesBrisay** [comment]
Try running it from the root directory of `presearch-packages`

**Comment by jejopl** [comment]
![createpackage](https://user-images.githubusercontent.com/32012330/48305011-d67e0800-e523-11e8-9316-0a770936fc19.png)

There was a problem with npm script. I've fixed it by changing npm script in the package.json file 
From this `"create-package": "./bin/create-package.sh"`
to this `"create-package": "./bin/create-package.sh || .\\bin\\create-package.sh"`

It wasn't working on windows because windows is using `\ `slash, and not `/`

**Comment by dskrenta** [comment]
Thanks for solving that, we'll update the npm script.

**Comment by dskrenta** [comment]
Windows script is located at `npm create-package-windows` as it was conflicting with the unix/linux version while in the same npm script.
