### ISSUE TITLE
Uncaught SyntaxError and Uncaught TypeError

### ISSUE THREAD

**Issue by mbiesiad** [PresearchOfficial/presearch-packages#161]
**Describe the bug**
Passing the appropriate parameter in `page=` can cause errors like **SyntaxError** and Uncaught **TypeError**.

**To Reproduce**
1. Go to: https://presearch.com/search?q=test&&page=%3Cscript%3E%3C/script%3E
(type for `page=` as parameter: `<script></script>`)
2. Check DevTools Console

**Expected behavior**
It's **secure** for mentioned case and appropriate **handled**.

**Screenshots**
Errors (DevConsole):
![errors](https://user-images.githubusercontent.com/18367606/187017138-0985451c-8158-4213-bf62-a8b6f7ff2d3e.PNG)

Site view:
![issue-1](https://user-images.githubusercontent.com/18367606/187017152-2cf8dd8b-c5e9-4b5d-b45b-4f3fab925037.PNG)

Site view for smaller size (pay attention to horizontal slider):
![issue-small-view](https://user-images.githubusercontent.com/18367606/187017161-50aac8ac-5b81-4e7a-b27d-d315ed83929a.PNG)

**Desktop :**
OS: Windows 10
Browser: Chrome (also applies to other browsers)
Version: 104

**Additional context**
Console:
```
search?q=test&&page=%3Cscript%3C/script%3E:6 **Uncaught SyntaxError**: Invalid or unexpected token (at search?q=test&&page=%3Cscript%3C/script%3E:6:15)
app.js:115 Loaded
app.js:115 **Uncaught TypeError**: Cannot read properties of undefined (reading 'split')
    at u (app.js:115:1307)
    at parcelRequire.QvaY.axios (app.js:115:1668)
    at f (app.js:1:468)
    at p (app.js:1:544)
    at parcelRequire.ElCy../css/main.scss (app.js:117:41)
    at f (app.js:1:468)
    at parcelRequire.V4IP (app.js:1:771)
    at app.js:1:1023
```

Info displayed on the site:

`"; window.requestQuery = "test"; window.localSettings = {"x-powered-by":true,"etag":"weak","env":"production","query parser":"extended","subdomain offset":2,"trust proxy":true,"views":"/app/views","jsonp callback name":"callback","view cache":true,"view engine":"pug","title":"Presearch","PRESEARCH_DOMAIN":"https://presearch.com","GATEWAY_ADDRESS":"eu-de-1.gateway.presearch.com","OLD_PRESEARCH_DOMAIN":"https://presearch.org","PRESEARCH_ACCOUNT_DOMAIN":"https://account.presearch.com","SEARCH_PROVIDERS_DOMAIN":"https://external.presearch.com","KEYWORDS_DOMAIN":"https://keywords.presearch.com","IMGCACHE_DOMAIN":"https://img.presearch.com","lang":"pl;q=0.8"}; window.PRESEARCH_DOMAIN = "https://presearch.com"; window.PRESEARCH_ACCOUNT_DOMAIN = "https://account.presearch.com"; window.OLD_PRESEARCH_DOMAIN = "https://presearch.org";`

Best wishes,

**Comment by jejopl** [comment]
Good catch @mbiesiad! We will push the fix shortly 🙏

**Comment by mbiesiad** [comment]
Sounds great! My pleasure, best wishes ✨

**Comment by jejopl** [comment]
The fix has been pushed to production, thanks!
