### ISSUE TITLE
Packages - problem with css

### ISSUE THREAD

**Issue by jejopl** [PresearchOfficial/presearch-packages#19]
![bug](https://user-images.githubusercontent.com/32012330/48505556-9da5a200-e847-11e8-8dcb-d78587ba6581.png)

e. g. if you are using `<h1>`, and you have multi-line text, the words are overlapping. I had the same issue with my package because by default all the text inherits line-height from the body element.

**Comment by BDesBrisay** [comment]
Thanks for posting this issue @jejopl we are currently aware of this and will resolve it in the next update to the engine along with a few other all around improvements.
