### ISSUE TITLE
Calculator:  Absurd accuracy - 52+ significant digits

### ISSUE THREAD

**Issue by morahan** [PresearchOfficial/presearch-packages#200]
**Describe the bug**
calculator  has too many decimals.  Especially considering the repetitive nature of it.  

Result:  = 0.7992277992277992277992277992277992277992277992277992277992277992

**To Reproduce**
search query "621/777"

**Expected behavior**
I think:  0.799227 would suffice.   

**Screenshots**
<img width="905" alt="Screenshot 2023-05-22 at 1 41 03 AM" src="https://github.com/PresearchOfficial/presearch-packages/assets/797254/1e155e75-97b7-4949-bb3e-f9a8ffae11ff">

**Comment by jejopl** [comment]
thanks for reporting, fixed in #204
