### ISSUE TITLE
inaccurate results for numerical searches

### ISSUE THREAD

**Issue by morahan** [PresearchOfficial/presearch-packages#201]
**Describe the bugS**
 1. When typing a simple multiplication into research, Commas throw off the Presearch to the extent that it doesn't even realize I'm asking it to do Math, and doesn't prompt the calculator 

2.  AI Results contradict the calculator.  
3. While I am typing a long number (I would like to see it fill the screen horizontally rather than stack vertically preemptively (as if there were not screen real estate to the right)) the animation pushing down the calculator is disorienting.  

**To Reproduce #1**
search queries "777,777,777,777,777 *12" and "777777777777777 *12"  yield different results

**Expected behavior**
same results for both searches.   Ignore the commas!  it is so helpful for humans to read a large number or count how many 7's are there.  

**To Reproduce #2**
search query "777,777,777,777,777 *12" then view what the AI has to say below.  

**Expected behavior**
AI should stay hidden when doing math.  Especially if it chimes in with the wrong answer!  

**To Reproduce #3**
type a large number into the calculator example, "777,777,777,777,777 *123456788900".  Notice that the numbers stay confined to the small calculator window and then jump to a second line rather than using the available screen real estate to the right. 

**Expected behavior**
Type out large numbers on one line.  Perhaps even reducing text size (to a point) to maintain 1 line 

**Screenshots**
<img width="907" alt="Screenshot 2023-05-22 at 1 53 05 AM" src="https://github.com/PresearchOfficial/presearch-packages/assets/797254/2f5910f5-0ab6-4e49-b86a-1650e61aceec">
<img width="795" alt="Screenshot 2023-05-22 at 1 55 26 AM" src="https://github.com/PresearchOfficial/presearch-packages/assets/797254/2f1acb7c-375f-49ed-b884-ee508579c974">
<img width="919" alt="Screenshot 2023-05-22 at 1 57 44 AM" src="https://github.com/PresearchOfficial/presearch-packages/assets/797254/f2967a9c-2bf7-4a0a-bb19-ea8fe80e1131">

**Desktop (please complete the following information):**
 - MacOS
 - Brave

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jejopl** [comment]
Thanks for reporting, fixed in #204
