### ISSUE TITLE
Not loaded image next to the Login button

### ISSUE THREAD

**Issue by mbiesiad** [PresearchOfficial/presearch-packages#228]
**Describe the bug**
Broken image close to the Login button.

**To Reproduce**
1. Go to the https://presearch.com/
2. Take a look at the upper right corner (upper left - btn with text 'Sign up to Earn').

**Expected behavior**
Fixed issue - nice view.

**Screenshots**
![bug](https://github.com/user-attachments/assets/91d45f46-9b3c-44f8-84b6-1668aab0d03e)

Checked with Brave browser as well as Firefox (the newest versions - 24-8-11)

**Additional context**
It looks like not loaded (for example.: blocked) image.

Best wishes,

**Comment by jejopl** [comment]
Hey, you are talking about P_ logo animation?


https://github.com/user-attachments/assets/c93997fb-ae5e-4c81-ad9a-64bea57bddff

**Comment by mbiesiad** [comment]
Hi, o wow! I was wrong. Sorry for that... After zooming in action, even in the screenshot from me I can see there 'P_' logo, now.

Thanks for your comment and reply. Best wishes,

**Comment by jejopl** [comment]
No worries, thanks for the feedback! ;-)
