### ISSUE TITLE
Trigger is not working for uppercase queries

### ISSUE THREAD

**Issue by jejopl** [PresearchOfficial/presearch-packages#24]
**Describe the bug**
The trigger is not working for uppercase queries. For example, in star wars quotes package, when
you search for `star wars quote` everything is okay, but if you start with uppercase `Star wars quote` the package will not be loaded. The same thing is with other packages.

The simple fix is to convert the queries to lower case like that:

```
function trigger(query) {
  query = query.toLowerCase();
  return query === 'starwars quote' || query === 'star wars quote';
}
```

**Comment by dskrenta** [comment]
Thanks for pointing this out, resolved in the most recent deploy.
