### ISSUE TITLE
map package issue

### ISSUE THREAD

**Issue by mad409** [PresearchOfficial/presearch-packages#37]
**Describe the bug**

The top of the page just shows the word map, not working.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mad409** [comment]
Nothing showing up when searching map other than the text map.

map

Created by PresearchOfficial
Version 1.0.0
Feedback

**Comment by jejopl** [comment]
hey @mad409, **math** package caused this issue. It's triggered when you enter map, sqrt, round etc. as a query. I've send a pull request with fix

**Comment by davidkeefe24** [comment]
@jejopl Good catch with this one! Definitely related to #46 and will be live soon.
