### ISSUE TITLE
Searching ticker with $

### ISSUE THREAD

**Issue by gftradco** [PresearchOfficial/presearch-packages#48]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Searching with a cryptocurrency's ticker works for most major coins but not for some of the smaller caps, or more ambiguous coins. BAT for example doesn't return the CoinMarketCap price info, like BTC does. (This is an awesome feature. Search with BTC and get the price data.) 
Could we add to this feature, maybe a dollar sign, $BAT, $BTC, $CRO etc. returns the CoinMarketCap price data?

**Comment by jejopl** [comment]
Hmm, I have all the data when I search for BAT

![obraz](https://user-images.githubusercontent.com/32012330/81093792-deddb600-8f02-11ea-89b2-dc5cc4683a5d.png)

**Comment by gftradco** [comment]
Hmm, it is pulling up BAT for me too, now. Thank you for taking a look at that. False alarm. Have a great day.
