### ISSUE TITLE
Cyrpto banner at top of coin searches in Dsearch

### ISSUE THREAD

**Issue by MrCartographer** [PresearchOfficial/presearch-packages#54]
The banner that Dsearch displays before search results when I type in "Dogecoin" is wonderful. Great stuff. 

I'd also like this for sports. Please type in "premier league" into google and see the banner display that google shows before the search results that has match results, statistics, the table, etc. It would be great to have that on Dsearch.

**Comment by jejopl** [comment]
Thanks for your suggestion, @MrCartographer. We will see what can we do ;-)
