### ISSUE TITLE
Floating decimal point issue

### ISSUE THREAD

**Issue by TwelfthGhast** [PresearchOfficial/presearch-packages#81]
**Describe the bug**

Some float operations do not result in the correct expected response.

**To Reproduce**
1. https://engine.presearch.org/search?q=316.7-133.4

**Expected behavior**

Expected output is 183.3; returned output is 183.29999999999998

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: 1.30.87

**Additional context**

**Comment by jejopl** [comment]
Thanks @TwelfthGhast and sorry for the late response 🙏 .
This issue has been fixed and it will be pushed to production soon.

Appreciate your support
