### ISSUE TITLE
Missing emoji-regex dependency

### ISSUE THREAD

**Issue by joshtom1** [PresearchOfficial/presearch-packages#86]
**Describe the bug**
When I run npm install it does not install emoji-regex. So when I try to cd server && npm start, I get an error saying that is missing module emoji-regex.

**To Reproduce**
1. Fork a new repository and clone it to your IDE
2. In presearch-packages, run npm install
3. cd server && npm start
4. Attempt to access http://localhost:4000/

**Expected behavior**
It should install all dependencies so that we can run the test server.

**Screenshots**
![image](https://user-images.githubusercontent.com/25560722/138969867-ac61c6cd-fdd0-48fe-8732-447e20cf2772.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version 1.31.87

**Smartphone (please complete the following information):**
N/A

**Additional context**
Just posting for reference in case other developers run into it. I imagine it will be fixed easily enough.

**Comment by jejopl** [comment]
thanks @ishan27596. I've pushed the changes to main branch.
