### ISSUE TITLE
Searching phone numbers shows calculations instead

### ISSUE THREAD

**Issue by redpill1** [PresearchOfficial/presearch-packages#90]
**Describe the bug**
When you search for a phone number say  (919) 438-6966, results on the top shows result of a computation as 
(919) 438-6966
395556.00

**To Reproduce**
1. See above

**Expected behavior**
Not sure if phone number format should rather be recognized as phone numbers and not show mathematical calculations. 

**Screenshots**
![image](https://user-images.githubusercontent.com/80494288/140008148-0189921a-06fa-48ab-9c98-c1e52c405f1a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version [e.g. 22] latest

My PRE id for bounty (?):  2637364

**Comment by jejopl** [comment]
Thanks @redpill1, I will take a look on that!

**Comment by jejopl** [comment]
thanks @redpill1, it has been fixed 🙏
